version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwe123
      POSTGRES_USER: dbuser
      POSTGRES_DB: flaskblog
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d flaskblog" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    ports:
      - 80:80
    command: bash -c "
      flask init-db
      && flask create-admin
      && flask run --host=0.0.0.0 --port=80
      "
    depends_on:
      db:
        condition: service_healthy
